"""Phase 4.5 showcase profile and frozen live-source contracts (P4.5-1)."""

from app.showcase.contracts import (
    LIVE_SOURCE_KINDS,
    LIVE_SOURCE_RESULT_FIELDS,
    LOCATOR_FIELDS,
    LOCATOR_KINDS_BY_SOURCE_KIND,
    MAX_DISPLAY_TEXT_LENGTH,
    MAX_LOCATOR_VALUE_LENGTH,
    MAX_TITLE_LENGTH,
    SCHEMA_VERSION,
    SHOWCASE_ENABLED_ENV,
    SHOWCASE_SOURCES_ENV,
    CapabilityState,
    EvidencePartition,
    ExecutionMode,
    Limitation,
    LiveSourceResultError,
    RecordType,
    ShowcaseCapabilities,
    SourceKind,
    resolve_capabilities,
    validate_live_source_result,
)

__all__ = [
    "LIVE_SOURCE_KINDS",
    "LIVE_SOURCE_RESULT_FIELDS",
    "LOCATOR_FIELDS",
    "LOCATOR_KINDS_BY_SOURCE_KIND",
    "MAX_DISPLAY_TEXT_LENGTH",
    "MAX_LOCATOR_VALUE_LENGTH",
    "MAX_TITLE_LENGTH",
    "SCHEMA_VERSION",
    "SHOWCASE_ENABLED_ENV",
    "SHOWCASE_SOURCES_ENV",
    "CapabilityState",
    "EvidencePartition",
    "ExecutionMode",
    "Limitation",
    "LiveSourceResultError",
    "RecordType",
    "SourceKind",
    "ShowcaseCapabilities",
    "resolve_capabilities",
    "validate_live_source_result",
]
